name = "the-crosser"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".svelte-kit/cloudflare"

[[kv_namespaces]]
binding = "SUBSCRIBERS"
id = "2945500736e54ff1974d1411ffbb2638"
